### ISSUE TITLE
TwitchPubSub object has no attribute OnRewardRedeemed

### ISSUE THREAD

**Issue by Spanden** [Encrypted-Thoughts/SLCB-ChannelPointsSFXTrigger#1]
FileName: .\Services\Scripts\ChannelPointsSFXTrigger\ChannelPointsSFXTrigger_StreamlabsSystem.py
Function: Start
LineNr: 99
Message: 'TwitchPubSub' object has no attribute 'OnRewardRedeemed'

**Comment by Encrypted-Thoughts** [comment]
Woops, looks like I forgot to update the TwitchLib.PubSub.dll and needed to change the headers for one of the twitch api calls.  Get the zip again from [Here](https://github.com/Encrypted-Thoughts/SLCB-ChannelPointsSFXTrigger/blob/master/ChannelPointsSFXTrigger.zip?raw=true) and see it works for you.
