### ISSUE TITLE
Getting error "An attempt was made to load an assembly from a network location"

### ISSUE THREAD

**Issue by markman641** [Encrypted-Thoughts/SLCB-ChannelPointsSFXTrigger#2]
Not sure if I'm doing something wrong, but I installed the script and I'm getting error: 

> An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

**Comment by Encrypted-Thoughts** [comment]
Think we talked about this on discord? maybe? 
Unblocking the script pack after downloading usually resolves this issue.
